### ISSUE TITLE
Method stubs not being generated

### ISSUE THREAD

**Issue by Cthulhu-Admin** [IL2CPP-Toolkit/Core#5]
Using IL2CPPDumper, the emitted assemblies include declarations and offsets for public methods. Example

```c#
namespace Client.Model
{
  [Token(Token = "0x2000003")]
  public class AppModel : SingleInstance<AppModel>
  {
     [Token(Token = "0x6000027")]
     [Address(Offset = "0x4DC7C0", RVA = "0x4DD9C0", VA = "0x1804DD9C0")]
     public UserReadGuard ReadUser(int? lockTimeoutMs = null) => (UserReadGuard) null;
  }  
}
```

I realize ReadUser() has its own dummy implementation and doesn't do anything but return null. However, it does include all the offset information that is required to invoke this method in the targeted process, provided we have an instance of AppModel.

Using IL2CPP-Toolkit, public properties and public static methods are included in the emitted assembly, including a functional implementation, but public member functions like ReadUser() are NOT included. This seams strange to me, as properties are also just member functions.

- Is the fact that stubs to invoke methods like ReadUser() are omitted intentional?
- If so, why?
- Is there some other way to invoke such methods that I'm missing, without having Offset, RVA and VA emitted for each method?

**Comment by dnchattan** [comment]
They are not currently implemented, but I am actually just now starting to work on support for instance methods, including support for calling them in the remote process. (I have already added support for this in RaidToolkit and will be back porting it to this framework as an additional support library)

**Comment by Cthulhu-Admin** [comment]
Hey @dnchattan

Thanks for the response. Interesting!

I actually looked at Raid-Toolkit when I started my project. Nice work! Unfortunately it is not what I was looking for. I do remember seeing some form of method invocation however. I think it "reverse engineered" method signatures and offsets at runtime and was largely type-less? I'm guessing most of that would occur while the interop assembly is generated.

Anyway, I would have given this a shot myself, but you are clearly a lot farther along than I am. Do you have any timeline expectations? Anything I could help with?

**Comment by dnchattan** [comment]
@Cthulhu-Admin you should take a look at the latest 2.x builds, which have a completely rewritten .net codegen.  I'm still working through some bugs, but this new version supports not only emitting the methods, but also calling them in the target process UI thread via gRPC.
